[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-android-api-level",
    "allow-get-name",
    "allow-get-byte-length",
    "allow-get-type",
    "allow-get-mime-type",
    "allow-get-metadata",
    "allow-get-thumbnail",
    "allow-get-thumbnail-base64",
    "allow-get-thumbnail-data-url",
    "allow-get-fs-path",
    "allow-list-volumes",
    "allow-create-new-public-file",
    "allow-create-new-public-image-file",
    "allow-create-new-public-video-file",
    "allow-create-new-public-audio-file",
    "allow-scan-public-file",
    "allow-request-public-files-permission",
    "allow-has-public-files-permission",
    "allow-create-new-file",
    "allow-create-dir-all",
    "allow-read-dir",
    "allow-check-picker-uri-permission",
    "allow-persist-picker-uri-permission",
    "allow-check-persisted-picker-uri-permission",
    "allow-release-persisted-picker-uri-permission",
    "allow-release-all-persisted-picker-uri-permissions",
    "allow-show-open-file-picker",
    "allow-show-open-dir-picker",
    "allow-show-save-file-picker",
    "allow-show-share-file-dialog",
    "allow-show-view-file-dialog",
    "allow-show-view-dir-dialog",

    "allow-persist-uri-permission",
    "allow-check-persisted-uri-permission",
    "allow-release-persisted-uri-permission",
    "allow-release-all-persisted-uri-permissions",
]