"$schema" = "schemas/schema.json"

# Based on code from tauri-plugin-fs crate
#
# Source:
# - https://github.com/tauri-apps/plugins-workspace/blob/69146fa8526a48039d60470304cdc775d973caa7/plugins/fs/permissions/scope.toml
# - Copyright 2019-2023 Tauri Programme within The Commons Conservancy
# - Licensed under the MIT License or the Apache 2.0 License
[[permission]]
identifier = "scope"
description = """
An empty permission you can use to modify the global scope.

## Example

```json
{
  "permissions": [
    "android-fs:all-without-delete",
    {
      "identifier": "android-fs:scope",
      "allow": [
        "$APPDATA/documents/**/*"
      ],
      "deny": [
        "$APPDATA/documents/secret.txt"
      ]
    }
  ]
}
```
"""